"""HTML report generation for the Rule Engine."""

from __future__ import annotations
from typing import Any
import json

REPORT_TEMPLATE = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Softlend — Credit Gap Analysis Report</title>
<style>
  :root {
    --bg: #0d1117;
    --card: #161b22;
    --border: #30363d;
    --text: #e6edf3;
    --muted: #8b949e;
    --high: #da3633;
    --medium: #d29922;
    --low: #3fb950;
    --green: #3fb950;
  }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    background: var(--bg);
    color: var(--text);
    padding: 2rem;
    max-width: 960px;
    margin: 0 auto;
  }
  h1 { font-size: 1.8rem; margin-bottom: 0.5rem; }
  h2 { font-size: 1.3rem; margin: 1.5rem 0 0.75rem; }
  .subtitle { color: var(--muted); margin-bottom: 1.5rem; }
  .summary {
    display: flex; gap: 1rem; flex-wrap: wrap; margin-bottom: 2rem;
  }
  .stat-card {
    background: var(--card);
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 1rem 1.5rem;
    flex: 1;
    min-width: 140px;
  }
  .stat-card .value { font-size: 2rem; font-weight: 700; }
  .stat-card .label { color: var(--muted); font-size: 0.85rem; margin-top: 0.25rem; }
  .gauge-container {
    background: var(--card);
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 1.5rem;
    margin-bottom: 2rem;
    text-align: center;
  }
  .gauge {
    width: 200px; height: 200px;
    margin: 0 auto;
    position: relative;
  }
  .gauge svg { transform: rotate(-90deg); }
  .gauge .bg { fill: none; stroke: var(--border); stroke-width: 12; }
  .gauge .fill { fill: none; stroke-width: 12; stroke-linecap: round; }
  .gauge-text {
    position: absolute; top: 50%; left: 50%;
    transform: translate(-50%, -50%);
    text-align: center;
  }
  .gauge-text .score { font-size: 2.5rem; font-weight: 800; }
  .gauge-text .label { font-size: 0.85rem; color: var(--muted); }
  .gap-card {
    background: var(--card);
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 1rem 1.25rem;
    margin-bottom: 0.75rem;
    display: flex;
    align-items: center;
    gap: 1rem;
  }
  .gap-card .impact-badge {
    padding: 0.25rem 0.6rem;
    border-radius: 4px;
    font-size: 0.75rem;
    font-weight: 600;
    text-transform: uppercase;
    flex-shrink: 0;
  }
  .impact-high { background: var(--high); color: #fff; }
  .impact-medium { background: var(--medium); color: #000; }
  .impact-low { background: var(--low); color: #000; }
  .gap-card .gain { color: var(--green); font-weight: 600; flex-shrink: 0; }
  .gap-card .action { flex: 1; color: var(--text); }
  .priority-matrix {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 1rem;
    margin-bottom: 2rem;
  }
  .quadrant {
    background: var(--card);
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 1rem;
    min-height: 120px;
  }
  .quadrant h3 { font-size: 0.85rem; margin-bottom: 0.5rem; }
  .quadrant ul { list-style: none; }
  .quadrant li { font-size: 0.85rem; padding: 0.2rem 0; color: var(--muted); }
  .footer { margin-top: 2rem; color: var(--muted); font-size: 0.8rem; text-align: center; }
</style>
</head>
<body>
  <h1>Credit Gap Analysis Report</h1>
  <p class="subtitle">Customer: {{customer_id}} &middot; Generated by Softlend Rule Engine</p>

  <div class="summary">
    <div class="stat-card">
      <div class="value">{{gaps_found}}</div>
      <div class="label">Gaps Found</div>
    </div>
    <div class="stat-card">
      <div class="value" style="color: var(--green);">+{{total_potential_score_gain}}</div>
      <div class="label">Potential Score Gain</div>
    </div>
  </div>

  <div class="gauge-container">
    <h2>Score Impact Overview</h2>
    <div style="margin-top: 1rem; display: flex; justify-content: center; gap: 2rem; flex-wrap: wrap;">
      {% for gap in gaps %}
      <div class="gap-card" style="flex-direction: column; text-align: center; min-width: 150px;">
        <span class="impact-badge impact-{{gap.impact}}">{{gap.impact}}</span>
        <strong>{{gap.id | replace('_', ' ') | title}}</strong>
        <span class="gain">+{{gap.estimated_score_gain}} pts</span>
      </div>
      {% endfor %}
    </div>
  </div>

  <h2>Detailed Gap Breakdown</h2>
  {% for gap in gaps %}
  <div class="gap-card">
    <span class="impact-badge impact-{{gap.impact}}">{{gap.impact}}</span>
    <span class="gain">+{{gap.estimated_score_gain}} pts</span>
    <span class="action">{{gap.action}}</span>
  </div>
  {% endfor %}

  <h2>Priority Matrix</h2>
  <div class="priority-matrix">
    <div class="quadrant" style="border-color: var(--high);">
      <h3 style="color: var(--high);">High Impact</h3>
      <ul>
      {% for gap in gaps if gap.impact == 'high' %}
        <li>+{{gap.estimated_score_gain}} pts &mdash; {{gap.id | replace('_', ' ') | title}}</li>
      {% else %}
        <li>No high-impact gaps</li>
      {% endfor %}
      </ul>
    </div>
    <div class="quadrant" style="border-color: var(--medium);">
      <h3 style="color: var(--medium);">Medium Impact</h3>
      <ul>
      {% for gap in gaps if gap.impact == 'medium' %}
        <li>+{{gap.estimated_score_gain}} pts &mdash; {{gap.id | replace('_', ' ') | title}}</li>
      {% else %}
        <li>No medium-impact gaps</li>
      {% endfor %}
      </ul>
    </div>
  </div>

  <div class="footer">
    Generated by Softlend Rule Engine &middot; Config-driven gap analysis
  </div>
</body>
</html>
"""


def generate_html_report(result: dict[str, Any], mode: str) -> str:
    """Generate an HTML report from engine results."""
    try:
        from jinja2 import Template
        template = Template(REPORT_TEMPLATE)
        return template.render(**result)
    except ImportError:
        html = f"""<!DOCTYPE html><html><body>
        <h1>Credit Gap Analysis Report</h1>
        <pre>{json.dumps(result, indent=2)}</pre>
        </body></html>"""
        return html
