version: 2

updates:
  - package-ecosystem: npm
    directory: /backend
    schedule:
      interval: weekly
    commit-message:
      prefix: chore
      prefix-development: chore

  - package-ecosystem: pip
    directory: /rule-engine
    schedule:
      interval: weekly
    commit-message:
      prefix: chore

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: chore
